---
# tasks file for docker

- name: Add an apt key for docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker
  apt:
    name: docker-ce
    state:  present

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
