image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  GITLAB_REGISTRY: '10.164.0.3:4567'

before_script:
  - cd reddit
#  - bundle install

build_job:
  image: docker:latest
  stage: build
  services:
  - docker:dind
  script:
    - echo 'Building'
 #   - cd reddit
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${GITLAB_REGISTRY}
    # - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${GITLAB_REGISTRY}
    # - docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
    # - docker build -t ${DOCKER_USER}/reddit:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} docker-monolith
    # - docker push ${DOCKER_USER}/reddit:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}
    - docker build -t ${GITLAB_REGISTRY}/homework/example2:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID} .
    # - docker run registry.example.com/my-group/my-project /script/to/run/tests
    - docker push ${GITLAB_REGISTRY}/homework/example2:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - bundle install
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
