---
- name: Docker container run
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Deploy docker container from Docker Hub
      docker_container:
        name: reddit
        image: "{{ docker_container_image }}"
        pull: yes
        state: started
        restart: yes
        ports:
        - "{{ docker_container_extport }}:{{ docker_container_intport }}"
