---
- name: Start node
  hosts: all
  become: true
  gather_facts: False

  tasks:
    - name: Restart a container
      docker_container:
        name: "{{ node }}"
        state: started
        restart: yes
