version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      net_back:
        aliases:
          - post_db
          - comment_db
  ui:
    build:
      context: ./ui
      dockerfile: ${UI_DOCKERFILE-Dockerfile}
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      net_front:

  post:
    build:
      context: ./post-py
      dockerfile: ${POST_DOCKERFILE-Dockerfile}

    image: ${USER_NAME}/post:${POST_VERSION}
    networks:
      net_back:
        aliases:
          - post
      net_front:
        aliases:
          - post
  comment:
    build:
      context: ./comment
      dockerfile: ${COMMENT_DOCKERFILE-Dockerfile}

    image: ${USER_NAME}/comment:${COMMENT_VERSION}
    networks:
      net_back:
        aliases:
          - comment
      net_front:
        aliases:
          - comment

volumes:
  post_db:

networks:
  net_back:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24

  net_front:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
